import "dotenv/config";
import mongoose from "mongoose";
import FormTemplate from "./models/FormTemplate.js";

const TEMPLATES = [
  {
    templateName: "Event Registration Form",
    description: "Collect attendee details for event registration",
    category: "Registration",
    icon: "🎫",
    color: "#3b82f6",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: true,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Company",
        type: "text",
        required: false,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Job Title",
        type: "text",
        required: false,
        enabled: true,
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Ticket Type",
        type: "select",
        required: true,
        enabled: true,
        options: ["Standard", "VIP", "Group"],
        order: 6,
      },
    ],
  },
  {
    templateName: "Customer Feedback Form",
    description: "Gather feedback from customers about their experience",
    category: "Feedback",
    icon: "⭐",
    color: "#f59e0b",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: false,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Rating",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Poor", "Fair", "Good", "Excellent"],
        order: 3,
      },
      {
        fieldId: "field4",
        label: "What went well?",
        type: "textarea",
        required: false,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "What could be improved?",
        type: "textarea",
        required: false,
        enabled: true,
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Would you recommend us?",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Yes", "No", "Maybe"],
        order: 6,
      },
    ],
  },
  {
    templateName: "Medical Registration Form",
    description: "Collect patient information for medical appointments",
    category: "Health",
    icon: "🏥",
    color: "#ef4444",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Date of Birth",
        type: "date",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Phone Number",
        type: "tel",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Medical Insurance ID",
        type: "text",
        required: false,
        enabled: true,
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Reason for Visit",
        type: "textarea",
        required: true,
        enabled: true,
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Current Medications",
        type: "textarea",
        required: false,
        enabled: true,
        order: 7,
      },
      {
        fieldId: "field8",
        label: "Allergies",
        type: "textarea",
        required: false,
        enabled: true,
        order: 8,
      },
    ],
  },
  {
    templateName: "Job Application Form",
    description: "Collect applicant information for job positions",
    category: "Application",
    icon: "💼",
    color: "#8b5cf6",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: true,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Position Applied For",
        type: "text",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Years of Experience",
        type: "number",
        required: true,
        enabled: true,
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Current Job Title",
        type: "text",
        required: false,
        enabled: true,
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Education Level",
        type: "select",
        required: true,
        enabled: true,
        options: ["High School", "Bachelor's", "Master's", "PhD"],
        order: 7,
      },
      {
        fieldId: "field8",
        label: "Why are you interested in this position?",
        type: "textarea",
        required: true,
        enabled: true,
        order: 8,
      },
    ],
  },
  {
    templateName: "Booking Request Form",
    description: "Collect booking details for reservations",
    category: "Booking",
    icon: "📅",
    color: "#06b6d4",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: true,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Check-in Date",
        type: "date",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Check-out Date",
        type: "date",
        required: true,
        enabled: true,
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Number of Guests",
        type: "number",
        required: true,
        enabled: true,
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Room Type",
        type: "select",
        required: true,
        enabled: true,
        options: ["Single", "Double", "Suite", "Deluxe"],
        order: 7,
      },
      {
        fieldId: "field8",
        label: "Special Requests",
        type: "textarea",
        required: false,
        enabled: true,
        order: 8,
      },
    ],
  },
  {
    templateName: "Customer Survey",
    description: "Conduct a comprehensive customer satisfaction survey",
    category: "Survey",
    icon: "📊",
    color: "#10b981",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "How often do you purchase from us?",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Weekly", "Monthly", "Quarterly", "Annually", "First time"],
        order: 2,
      },
      {
        fieldId: "field3",
        label: "How satisfied are you with our service?",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Very Unsatisfied", "Unsatisfied", "Neutral", "Satisfied", "Very Satisfied"],
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Rate our product quality",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
        order: 4,
      },
      {
        fieldId: "field5",
        label: "How would you rate our pricing?",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Too Expensive", "Expensive", "Fair", "Good Value", "Excellent Value"],
        order: 5,
      },
      {
        fieldId: "field6",
        label: "What is your age group?",
        type: "select",
        required: false,
        enabled: true,
        options: ["18-25", "26-35", "36-45", "46-55", "56-65", "66+"],
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Additional comments",
        type: "textarea",
        required: false,
        enabled: true,
        order: 7,
      },
    ],
  },
  {
    templateName: "Donation Form",
    description: "Collect donations for charitable organizations",
    category: "Donation",
    icon: "❤️",
    color: "#ec4899",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: false,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Donation Amount",
        type: "number",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Donation Type",
        type: "select",
        required: true,
        enabled: true,
        options: ["One-time", "Monthly", "Quarterly", "Annually"],
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Campaign Interest",
        type: "select",
        required: false,
        enabled: true,
        options: ["Education", "Healthcare", "Environmental", "Community", "All"],
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Make your donation anonymous?",
        type: "checkbox",
        required: false,
        enabled: true,
        order: 7,
      },
      {
        fieldId: "field8",
        label: "Special message",
        type: "textarea",
        required: false,
        enabled: true,
        order: 8,
      },
    ],
  },
  {
    templateName: "Membership Application",
    description: "Collect information for membership programs",
    category: "Membership",
    icon: "🎖️",
    color: "#f97316",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: true,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Date of Birth",
        type: "date",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Membership Type",
        type: "select",
        required: true,
        enabled: true,
        options: ["Basic", "Premium", "Platinum"],
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Address",
        type: "textarea",
        required: true,
        enabled: true,
        order: 6,
      },
      {
        fieldId: "field7",
        label: "Interests",
        type: "textarea",
        required: false,
        enabled: true,
        order: 7,
      },
      {
        fieldId: "field8",
        label: "I agree to the terms and conditions",
        type: "checkbox",
        required: true,
        enabled: true,
        order: 8,
      },
    ],
  },
  {
    templateName: "Event Feedback Form",
    description: "Collect feedback after an event",
    category: "Event",
    icon: "🎪",
    color: "#14b8a6",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: false,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Event Rating",
        type: "radio",
        required: true,
        enabled: true,
        options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"],
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Venue Quality",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Poor", "Fair", "Good", "Excellent"],
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Organization Quality",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Poor", "Fair", "Good", "Excellent"],
        order: 5,
      },
      {
        fieldId: "field6",
        label: "What did you like most about the event?",
        type: "textarea",
        required: true,
        enabled: true,
        order: 6,
      },
      {
        fieldId: "field7",
        label: "What could be improved?",
        type: "textarea",
        required: false,
        enabled: true,
        order: 7,
      },
      {
        fieldId: "field8",
        label: "Would you attend similar events in future?",
        type: "radio",
        required: true,
        enabled: true,
        options: ["Yes", "No", "Maybe"],
        order: 8,
      },
    ],
  },
  {
    templateName: "Contact Us Form",
    description: "Collect inquiries and messages from visitors",
    category: "Other",
    icon: "📧",
    color: "#6366f1",
    isIndustryTemplate: true,
    fields: [
      {
        fieldId: "field1",
        label: "Full Name",
        type: "text",
        required: true,
        enabled: true,
        order: 1,
      },
      {
        fieldId: "field2",
        label: "Email Address",
        type: "email",
        required: true,
        enabled: true,
        order: 2,
      },
      {
        fieldId: "field3",
        label: "Phone Number",
        type: "tel",
        required: false,
        enabled: true,
        order: 3,
      },
      {
        fieldId: "field4",
        label: "Subject",
        type: "text",
        required: true,
        enabled: true,
        order: 4,
      },
      {
        fieldId: "field5",
        label: "Category",
        type: "select",
        required: true,
        enabled: true,
        options: ["General Inquiry", "Support", "Partnership", "Feedback", "Other"],
        order: 5,
      },
      {
        fieldId: "field6",
        label: "Message",
        type: "textarea",
        required: true,
        enabled: true,
        order: 6,
      },
    ],
  },
];

async function seedTemplates() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    const existingCount = await FormTemplate.countDocuments({
      isIndustryTemplate: true,
    });
    if (existingCount > 0) {
      console.log(`Found ${existingCount} existing industry templates. Skipping seed.`);
      await mongoose.disconnect();
      return;
    }

    const result = await FormTemplate.insertMany(TEMPLATES);
    console.log(`✅ Successfully seeded ${result.length} industry templates!`);
    result.forEach((template) => {
      console.log(`  - ${template.templateName} (${template.category})`);
    });

    await mongoose.disconnect();
  } catch (error) {
    console.error("Error seeding templates:", error);
    process.exit(1);
  }
}

seedTemplates();
